### ISSUE TITLE
Failure [DELETE_FAILED_INTERNAL_ERROR]

### ISSUE THREAD

**Issue by ppav** [cesarferreira/purrge#1]
<a href="http://tinypic.com?ref=sevvr4" target="_blank"><img src="http://i66.tinypic.com/sevvr4.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://tinypic.com?ref=2nbehwn" target="_blank"><img src="http://i67.tinypic.com/2nbehwn.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

### Fix 
`.map(item => item.replace(/^\s+|\s+$/g, ""));`

**Comment by cesarferreira** [comment]
Hey,
what you mean? This is supposed to happen because you cannot uninstall the `youtube` app

**Comment by ppav** [comment]
Of course i can. Example video with a problem https://youtu.be/b5aI6Zb1JZk

**Comment by cesarferreira** [comment]
Ahhh I get it!
My youtube app is a system app and I can't uninstall it, that's why I thought it was a mistake.
Want to make a pull request with this change so you get associated with the fix mate?

**Comment by ppav** [comment]
it would be great

**Comment by cesarferreira** [comment]
I'm waiting then :)

**Comment by cesarferreira** [comment]
it's working on `1.1.2` thanks
