### ISSUE TITLE
What does it do exactly, that adb can't do already?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [cesarferreira/purrge#4]
Just a bit nicer UI ?

**Comment by cesarferreira** [comment]
This uses `adb` on the background, it's not a replacement... but how fast can you manually uninstall/clear app data of a given app?

This allows you to do it in like `4 seconds` and it even uses [fuzzy matching](https://en.wikipedia.org/wiki/Fuzzy_matching_(computer-assisted_translation)) so you can have a typo in your search and still find the right one

**Comment by AndroidDeveloperLB** [comment]
ok then . Closing this one.

**Comment by AndroidDeveloperLB** [comment]
BTW, if you like doing such operations, here's an app I made that does it (requires rooted device) on the go:
https://play.google.com/store/apps/details?id=com.lb.app_manager&hl=en

**Comment by AndroidDeveloperLB** [comment]
Just thought it could be useful for me too, to use this repo as well.

**Comment by ismdcf** [comment]
If we are using an android app. This could be done using the settings menu. @AndroidDeveloperLB this could be used for faster ADB uninstall

**Comment by AndroidDeveloperLB** [comment]
@ismdcf Yes. All depends on your needs and usage.
